---
- hosts: all 
  remote_user: ubuntu 
  become: true
  gather_facts: no 
  tasks: 
  #for linux server
  - name: Install postgresql
    apt:  
      name: postgresql
      state: latest
      update_cache: yes
      cache_valid_time: "900"
    
  - name: Remove postgresql
    apt:  
      name: postgresql
      state: absent



