- hosts: localhost
  gather_facts: no
 
  tasks:
  - name: Delete EC2 instance by Ansible
    ec2_instance:
      name: "EC2-instance-Ansible"
      state: absent
      filters:
        instance-state-name: running
      region: ap-south-1
     
  
#cmd=ansible-playbook --ask-vault-pass AWSInfrastructureAnsible/delete-ec2-ansible.yaml
#password=123
#this will delete the ec2 instance
