--- 
- hosts: localhost
  gather_facts: no #this is to speed up the playbook so that it runs faster

  tasks:
  - name: s3 by Ansible
    aws_s3:
      bucket: elasticbeanstalk-ap-south-1-941812274699
      object: ansible/ansible.jenkinsfile
      src: /var/jenkins_home/workspace/ansible/ansible.jenkinsfile
      mode: put
      
  #cmd
  #ansible-playbook --ask-vault-pass AWSInfrastructureAnsible/s3.yaml
#password=123
