---
- hosts: all 
  become: false
  gather_facts: no
  tasks: 
  #for windows server
    - name: download notepad++ on server
      win_chocolatey:
        name: notepadplusplus
        state: present

    - name: download sql server
      win_chocolatey:
        name: sql-server-management-studio
        state: present



#cmd=ansible-playbook -i WindowsServer/windows-server.yaml WindowsServer/installsoftware.yaml
