
---
- hosts: all
  remote_user: root #for creating ssh connection
  become: true
  gather_facts: no
  tasks: #playbooks executes tasks more than once
  - name: Install postgresql
    apt:  #package manager to install postgreas
      name: postgresql
      state: latest #ansible works in past tense
    notify:
      - Restart nginx
    
  - name: Install nginx
    apt:  #package manager to install nginx
      name: nginx
      state: latest #ansible works in past tense
    notify: 
      - Restart nginx
  

  - name: Remove nginx
    apt:  #package manager to install 
      name: nginx
      state: absent


  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted 

 
  
#ansible-playbook -i aws/aws.yaml playbooks/handler.yaml
