- hosts: localhost
  vars:
    instance_ids:
      - "{{ instanceid_1 }}"
      - "{{ instanceid_2 }}"
  tasks:
  - name: restart EC2 instance by Ansible
    ec2_instance:
      instance_ids: "{{ instance_ids }}"
      state: restarted
      region: ap-south-1
    
  
#cmd=ansible-playbook --ask-vault-pass  EC2-Instances/restart.yaml

