#before starting this we encrypted the credential.yaml
#using cmd=ansible-vault encrypt EC2-Instances/credential.yaml
#password=123
- hosts: localhost
  vars:
    instance_ids:
      - "{{ instanceid_1 }}"
      - "{{ instanceid_2 }}"
     
 
  tasks:
  - name: start EC2 instance by Ansible
  #code from https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_module.html
  #starting with - name: start an instance with a public IP address

    ec2_instance:
      instance_ids: "{{ instance_ids }}"   
      state: running
      region: ap-south-1
      
      
  
#cmd=ansible-playbook --ask-vault-pass  EC2-Instances/start.yaml
#password=123


#this will start mutiple the ec2 instance
