
- hosts: localhost
  vars:
    instance_ids:
      - "{{ instanceid_1 }}"
      - "{{ instanceid_2 }}"
  tasks:
  - name: start EC2 instance by Ansible
    ec2_instance:
      instance_ids: "{{ instance_ids }}"   
      state: running
      region: ap-south-1
      
      
  
#cmd=ansible-playbook --ask-vault-pass  EC2-Instances/start.yaml



